/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

// PRECISA ARRUMAR LÓGICO DO CÓDIGO 


package visao;

import javax.swing.JOptionPane;
import sql.SqlEntradaEstoque;
import sql.SqlFornecedor;
import sql.SqlProduto;

/**
 *
 * @author Aluno
 */
public class EntradaEstoque extends javax.swing.JFrame {
    SqlEntradaEstoque compra = new SqlEntradaEstoque();
    SqlFornecedor forn = new SqlFornecedor();
    SqlProduto prod = new SqlProduto();


    /**
     * Creates new form Produto
     */
    public EntradaEstoque() {
        initComponents();
    }
    
    public void limpar(){
        tfCodFornecedor.setText("");
        tfCodProd.setText("");
        tfDataEntEstoque.setText("");
        tfValor.setText("");
        tfQtd.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dtEntradaEstoque = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        cod_Fornec = new javax.swing.JLabel();
        tfCodFornecedor = new javax.swing.JTextField();
        cod_Produto = new javax.swing.JLabel();
        tfDataEntEstoque = new javax.swing.JFormattedTextField();
        botaoConfirma_EntEstoque = new javax.swing.JButton();
        botaoLimpar_EntEstoque = new javax.swing.JButton();
        botaoVoltaMenu_EntEstoque = new javax.swing.JButton();
        cod_Fornec1 = new javax.swing.JLabel();
        tfCodCompra = new javax.swing.JTextField();
        tfCodProd = new javax.swing.JTextField();
        valor1 = new javax.swing.JLabel();
        tfQtd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de Estoque"));

        dtEntradaEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtEntradaEstoque.setText("Data Entrada Estoque:");

        valor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valor.setText("Valor:");

        cod_Fornec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Fornec.setText("Cod. Fornecedor:");

        tfCodFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodFornecedorActionPerformed(evt);
            }
        });

        cod_Produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Produto.setText("Cod. Produto:");

        try {
            tfDataEntEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoConfirma_EntEstoque.setText("Confirmar");
        botaoConfirma_EntEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirma_EntEstoqueActionPerformed(evt);
            }
        });

        botaoLimpar_EntEstoque.setText("Limpar");
        botaoLimpar_EntEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar_EntEstoqueActionPerformed(evt);
            }
        });

        botaoVoltaMenu_EntEstoque.setText("Voltar para o Menu");
        botaoVoltaMenu_EntEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltaMenu_EntEstoqueActionPerformed(evt);
            }
        });

        cod_Fornec1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Fornec1.setText("Cod. Compra");

        tfCodCompra.setEditable(false);
        tfCodCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodCompraActionPerformed(evt);
            }
        });

        valor1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valor1.setText("Qtd:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valor)
                        .addGap(18, 18, 18)
                        .addComponent(tfValor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoConfirma_EntEstoque)
                        .addGap(29, 29, 29)
                        .addComponent(botaoLimpar_EntEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(botaoVoltaMenu_EntEstoque))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cod_Produto)
                            .addComponent(cod_Fornec)
                            .addComponent(cod_Fornec1))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodCompra)
                            .addComponent(tfCodFornecedor)
                            .addComponent(tfCodProd)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dtEntradaEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(tfDataEntEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valor1)
                        .addGap(18, 18, 18)
                        .addComponent(tfQtd)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_Fornec1)
                    .addComponent(tfCodCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_Fornec))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_Produto)
                    .addComponent(tfCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtEntradaEstoque)
                    .addComponent(tfDataEntEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor1)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltaMenu_EntEstoque)
                    .addComponent(botaoConfirma_EntEstoque)
                    .addComponent(botaoLimpar_EntEstoque))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Entrada de estoque");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirma_EntEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirma_EntEstoqueActionPerformed
    int idForn = forn.consultarId();
    int idProd = prod.consultarId();
    compra.gravar(idForn, idProd, tfDataEntEstoque.getText(),tfValor.getText(),(Integer.parseInt(tfQtd.getText())));  
        
    limpar(); // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirma_EntEstoqueActionPerformed

    private void tfCodFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodFornecedorActionPerformed

    private void botaoVoltaMenu_EntEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltaMenu_EntEstoqueActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltaMenu_EntEstoqueActionPerformed

    private void tfCodCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodCompraActionPerformed

    private void botaoLimpar_EntEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar_EntEstoqueActionPerformed
    limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimpar_EntEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaEstoque().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirma_EntEstoque;
    private javax.swing.JButton botaoLimpar_EntEstoque;
    private javax.swing.JButton botaoVoltaMenu_EntEstoque;
    private javax.swing.JLabel cod_Fornec;
    private javax.swing.JLabel cod_Fornec1;
    private javax.swing.JLabel cod_Produto;
    private javax.swing.JLabel dtEntradaEstoque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCodCompra;
    private javax.swing.JTextField tfCodFornecedor;
    private javax.swing.JTextField tfCodProd;
    private javax.swing.JFormattedTextField tfDataEntEstoque;
    private javax.swing.JTextField tfQtd;
    private javax.swing.JTextField tfValor;
    private javax.swing.JLabel valor;
    private javax.swing.JLabel valor1;
    // End of variables declaration//GEN-END:variables

}
