/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//implementada 22/11/2020

package visao;

import javax.swing.JOptionPane;
import sql.SqlProduto;

/**
 *
 * @author Aluno
 */
public class Produto extends javax.swing.JFrame {
    
    SqlProduto prod = new SqlProduto();

    
    public void limpar(){   
        tfNomeProd.setText("");
        jtDescricaoProd.setText("");
        tfValorProd.setText("");
    }
    

    /**
     * Creates new form Produto
     */
    public Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        descricao_Produto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescricaoProd = new javax.swing.JTextArea();
        valor_Produto = new javax.swing.JLabel();
        cod_Produto = new javax.swing.JLabel();
        tfNomeProd = new javax.swing.JFormattedTextField();
        tfCodProd = new javax.swing.JFormattedTextField();
        descricao_Produto1 = new javax.swing.JLabel();
        tfValorProd = new javax.swing.JFormattedTextField();
        botaoSalvar_Produto = new javax.swing.JButton();
        botaoLimpar_Produto = new javax.swing.JButton();
        botaoVoltaMenu_Produto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        descricao_Produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricao_Produto.setText("Descrição:");

        jtDescricaoProd.setColumns(20);
        jtDescricaoProd.setRows(5);
        jScrollPane1.setViewportView(jtDescricaoProd);

        valor_Produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valor_Produto.setText("Valor unitário:");

        cod_Produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Produto.setText("Cod.:");

        tfCodProd.setEditable(false);

        descricao_Produto1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descricao_Produto1.setText("Nome Prod:");

        botaoSalvar_Produto.setText("Salvar");
        botaoSalvar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvar_ProdutoActionPerformed(evt);
            }
        });

        botaoLimpar_Produto.setText("Limpar");
        botaoLimpar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar_ProdutoActionPerformed(evt);
            }
        });

        botaoVoltaMenu_Produto.setText("Voltar para o Menu");
        botaoVoltaMenu_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltaMenu_ProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botaoSalvar_Produto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimpar_Produto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltaMenu_Produto))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cod_Produto)
                        .addGap(59, 59, 59)
                        .addComponent(tfCodProd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricao_Produto1)
                            .addComponent(descricao_Produto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(tfNomeProd)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valor_Produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorProd)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_Produto)
                    .addComponent(tfCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricao_Produto1)
                    .addComponent(tfNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(descricao_Produto)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor_Produto)
                    .addComponent(tfValorProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar_Produto)
                    .addComponent(botaoLimpar_Produto)
                    .addComponent(botaoVoltaMenu_Produto)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltaMenu_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltaMenu_ProdutoActionPerformed
        dispose();
    }//GEN-LAST:event_botaoVoltaMenu_ProdutoActionPerformed

    private void botaoLimpar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar_ProdutoActionPerformed
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimpar_ProdutoActionPerformed

    private void botaoSalvar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvar_ProdutoActionPerformed
        int id = prod.consultarId();
        prod.gravar(id, tfNomeProd.getText(), jtDescricaoProd.getText(), tfValorProd.getText());
        limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSalvar_ProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLimpar_Produto;
    private javax.swing.JButton botaoSalvar_Produto;
    private javax.swing.JButton botaoVoltaMenu_Produto;
    private javax.swing.JLabel cod_Produto;
    private javax.swing.JLabel descricao_Produto;
    private javax.swing.JLabel descricao_Produto1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtDescricaoProd;
    private javax.swing.JFormattedTextField tfCodProd;
    private javax.swing.JFormattedTextField tfNomeProd;
    private javax.swing.JFormattedTextField tfValorProd;
    private javax.swing.JLabel valor_Produto;
    // End of variables declaration//GEN-END:variables
}
