/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

// PRECISA ARRUMAR LÓGICA DO CÓDIGO 

package visao;

import sql.SqlCliente;
import sql.SqlProduto;
import sql.SqlSaidaEstoque;


/**
 *
 * @author Aluno
 */
public class SaidaEstoque extends javax.swing.JFrame {
    SqlSaidaEstoque pedido = new SqlSaidaEstoque();
    SqlCliente cli = new SqlCliente();
    SqlProduto prod = new SqlProduto();

    /**
     * Creates new form Vendas
     */
    public SaidaEstoque() {
        initComponents();
    }

    public void limpar(){
        tfCodCliente.setText("");
        tfCodProd.setText("");
        tfDataSaidaEstoque.setText("");
        tfValor.setText("");
        tfQtd.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cod_Cliente = new javax.swing.JLabel();
        cod_Produto = new javax.swing.JLabel();
        tfCodPedido = new javax.swing.JTextField();
        tfCodProd = new javax.swing.JTextField();
        dtSaidaEstoque = new javax.swing.JLabel();
        tfDataSaidaEstoque = new javax.swing.JFormattedTextField();
        valorSaida = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        qtd = new javax.swing.JLabel();
        tfQtd = new javax.swing.JTextField();
        botaoConfirma_SaidaEstoque = new javax.swing.JButton();
        botaoVoltaMenu_SaidaEstoque = new javax.swing.JButton();
        botaoLimpar_SaidaEstoque = new javax.swing.JButton();
        cod_Cliente1 = new javax.swing.JLabel();
        tfCodCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saida de Estoque"));

        cod_Cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Cliente.setText("Cod. Cliente:");

        cod_Produto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Produto.setText("Cod. Produto:");

        tfCodPedido.setEditable(false);

        dtSaidaEstoque.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dtSaidaEstoque.setText("Data Saída do Estoque:");

        valorSaida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valorSaida.setText("Valor:");

        qtd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtd.setText("Qtd.:");

        botaoConfirma_SaidaEstoque.setText("Confirmar");
        botaoConfirma_SaidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirma_SaidaEstoqueActionPerformed(evt);
            }
        });

        botaoVoltaMenu_SaidaEstoque.setText("Voltar para o Menu");
        botaoVoltaMenu_SaidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltaMenu_SaidaEstoqueActionPerformed(evt);
            }
        });

        botaoLimpar_SaidaEstoque.setText("Limpar");
        botaoLimpar_SaidaEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar_SaidaEstoqueActionPerformed(evt);
            }
        });

        cod_Cliente1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cod_Cliente1.setText("Cod. Pedido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoConfirma_SaidaEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(botaoLimpar_SaidaEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(botaoVoltaMenu_SaidaEstoque)
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(valorSaida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(qtd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dtSaidaEstoque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfDataSaidaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 124, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cod_Cliente1)
                        .addGap(18, 18, 18)
                        .addComponent(tfCodPedido)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cod_Cliente)
                                .addGap(18, 18, 18)
                                .addComponent(tfCodCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cod_Produto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCodProd)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_Cliente1)
                    .addComponent(tfCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_Cliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cod_Produto)
                    .addComponent(tfCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtSaidaEstoque)
                    .addComponent(tfDataSaidaEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorSaida)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtd)
                    .addComponent(tfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltaMenu_SaidaEstoque)
                    .addComponent(botaoLimpar_SaidaEstoque)
                    .addComponent(botaoConfirma_SaidaEstoque))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.getAccessibleContext().setAccessibleName("Saída de estoque");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltaMenu_SaidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltaMenu_SaidaEstoqueActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoVoltaMenu_SaidaEstoqueActionPerformed

    private void botaoLimpar_SaidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar_SaidaEstoqueActionPerformed
    limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimpar_SaidaEstoqueActionPerformed

    private void botaoConfirma_SaidaEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirma_SaidaEstoqueActionPerformed
    int idCli = cli.consultarId();
    int idProd = prod.consultarId();
    pedido.gravar(idCli, idProd, tfDataSaidaEstoque.getText(),tfValor.getText(),(Integer.parseInt(tfQtd.getText()))); 
        
    limpar();        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirma_SaidaEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaEstoque().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirma_SaidaEstoque;
    private javax.swing.JButton botaoLimpar_SaidaEstoque;
    private javax.swing.JButton botaoVoltaMenu_SaidaEstoque;
    private javax.swing.JLabel cod_Cliente;
    private javax.swing.JLabel cod_Cliente1;
    private javax.swing.JLabel cod_Produto;
    private javax.swing.JLabel dtSaidaEstoque;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel qtd;
    private javax.swing.JTextField tfCodCliente;
    private javax.swing.JTextField tfCodPedido;
    private javax.swing.JTextField tfCodProd;
    private javax.swing.JFormattedTextField tfDataSaidaEstoque;
    private javax.swing.JTextField tfQtd;
    private javax.swing.JTextField tfValor;
    private javax.swing.JLabel valorSaida;
    // End of variables declaration//GEN-END:variables
}
